config/routes.rb
BitcoinBank::Application.routes.draw do

  resources :invoices, :only => [:index, :new, :create, :show, :destroy]

  resource :user, :only => [:edit, :update] do
    get :ga_otp_configuration
    post :reset_ga_otp_secret
    put :update_password
    get :edit_password

    resources :yubikeys, :only => [:index, :create, :destroy]
    resources :bank_accounts, :only => [:index, :create, :destroy]
    resources :tickets do
      resources :comments, :only => :create
      member do
        post :close
        post :reopen
        post :solve
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # These routes need some loving :/
  resource :chart, :path => "charts", :only => [] do
    get :price
  end

  resource :account, :only => [:show] do
    match '/balance/:currency',
      :action => 'balance',
      :as => 'balance',
      :only => :get

    get :deposit
    get :pecunix_deposit_form

    resources :transfers, :only => [:index, :new, :create, :show]

    resources :trades,
      :only => [:index]

    resources :invoices

    resources :trade_orders, :only => [:index, :new, :create, :destroy] do
      post :activate
    end
  end

  match "/s/:name" => "static_pages#show", :as => :static

  match '/third_party_callbacks/:action',
    :controller => :third_party_callbacks

  namespace :admin do
    %w{ announcements yubikeys static_pages currencies tickets comments }.each { |r| resources(r.to_sym) {as_routes} }

    resources :pending_transfers do
      as_routes

      member do
        post :process_tx
      end
    end

    resources :users do
      as_routes

      member do
        get :balances
      end

      resources :account_operations do
        as_routes
      end
    end

    match '/balances', :to => 'informations#balances', :as => :balances
  end

  match '/qrcode/:data.png' => 'qrcodes#show', :as => :qrcode

  match '/order_book' => 'trade_orders#book'

  match '/trades' => 'trades#all_trades'

  match '/ticker' => 'trades#ticker'

  match '/economy' => 'informations#economy', :as => :economy

  match '/support' => 'informations#support', :as => :support

  root :to => 'informations#welcome'
end

app/models/transfer.rb
class Transfer < AccountOperation
  include ActiveRecord::Transitions

  before_validation :round_amount,
    :on => :create  
  
  after_create :execute

  validates :amount,
    :numericality => true,
    :user_balance => true,
    :minimal_amount => true,
    :maximal_amount => true,
    :negative => true

  validates :currency,
    :inclusion => { :in => ["LRUSD", "LREUR", "EUR", "BTC"] }

  def type_name
    type.gsub(/Transfer$/, "").underscore.gsub(/\_/, " ").titleize
  end

  state_machine do
    state :pending
    state :processed

    event :process do
      transitions :to => :processed,
        :from => :pending
    end
  end

  def self.from_params(params)
    transfer = class_for_transfer(params[:currency]).new(params)
   
    if transfer.amount
      transfer.amount = -transfer.amount.abs 
    end
    
    transfer
  end

  def round_amount
    unless amount.nil? || amount.zero?
      self.amount = self.class.round_amount(amount, currency)
    end
  end

  def self.minimal_amount_for(currency)
    currency = currency.to_s.downcase.to_sym

    if [:lrusd, :lreur].include?(currency)
      BigDecimal("0.02")
    elsif currency == :eur
      BigDecimal("30.0")
    elsif currency == :btc
      BigDecimal("0.05")
    else
      raise RuntimeError.new("Invalid currency")
    end
  end  

  def self.round_amount(amount, currency)
    currency = currency.to_s.downcase.to_sym
    amount = amount.to_f if amount.is_a?(Fixnum)
    amount.to_d.round(2, BigDecimal::ROUND_DOWN)
  end
  
  def self.class_for_transfer(currency)
    currency = currency.to_s.downcase.to_sym
    if currency == :eur
      WireTransfer
    elsif [:lrusd, :lreur].include?(currency)
      LibertyReserveTransfer
    elsif currency == :btc
      BitcoinTransfer
    else
      raise RuntimeError.new("Invalid currency")
    end
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  respond_to :html, :json
  
  def index
    @transfers = current_user.account_operations.paginate(:page => params[:page], :per_page => 16)
    respond_with @transfers
  end

  def new
    if params[:currency] == "EUR"
      @transfer = WireTransfer.new(:currency => "EUR")
      @transfer.build_bank_account
      fetch_bank_accounts
    else
      @transfer = Transfer.new(:currency => params[:currency] || "LRUSD")
    end
  end
  
  def show
    @transfer = current_user.account_operations.find(params[:id])
    respond_with @transfer
  end
  
  def create
    @transfer = Transfer.from_params(params[:transfer])
    @transfer.account = current_user

    if @transfer.is_a?(WireTransfer) && @transfer.bank_account
      @transfer.bank_account.user_id = current_user.id
    end
    
    Operation.transaction do
      o = Operation.create!
      o.account_operations << @transfer
      o.account_operations << AccountOperation.new do |ao|
        ao.amount = @transfer.amount && @transfer.amount.abs
        ao.currency = @transfer.currency
        ao.account = Account.storage_account_for(@transfer.currency)
      end
      
      raise(ActiveRecord::Rollback) unless o.save
    end

    unless @transfer.new_record?
      respond_with do |format|
        format.html do
          redirect_to account_transfers_path,
            :notice => I18n.t("transfers.index.successful.#{@transfer.state}", :amount => @transfer.amount.abs, :currency => @transfer.currency)
        end
          
        format.json { render :json => @transfer }
      end
    else
      fetch_bank_accounts
      render :action => :new
    end
  end
  
  
  protected
  
  def fetch_bank_accounts
    @bank_accounts = current_user.bank_accounts.map { |ba| [ba.iban, ba.id] }
  end
end

app/helpers/admin/transfers_helper.rb
module Admin::TransfersHelper
  def user_column(record)
    record.user.account
  end
end

app/helpers/transfers_helper.rb
module TransfersHelper
  def color_for(transfer)
    transfer.amount > 0 ? (transfer.confirmed? ? "green" : "unconfirmed") : "red"
  end

  def confirmation_tooltip_for(transfer)
    unless transfer.confirmed?
      t :confirmations_left, :count => (Transfer::MIN_BTC_CONFIRMATIONS - transfer.bt_tx_confirmations)
    end
  end

  def transfer_details(transfer)
    link_to(image_tag("details.png", :alt => t(".details"), :title => t(".details")), account_transfer_path(transfer))
  end

  def transfer_state(state, options = {})
    content_tag :span,
      :class => ["transfer-state", color_for_transfer_state(state)] do
      "#{options[:icon] ? image_tag("#{state}.png", :class => "state-icon") : ""} #{options[:message]}".strip.html_safe
    end
  end

  def color_for_transfer_state(state)
    case state
    when "pending"  then   "orange"
    when "processed"  then  "green"
    end
  end
end

app/views/transfers/_lr_sci_form.html.erb
<form id="add_lr" action="https://sci.libertyreserve.com/en" method="POST">
  <input type="hidden" name="lr_acc" value="<%= BitcoinBank::LibertyReserve['account'] %>" />

  <input type="hidden" name="lr_store" value="<%= BitcoinBank::LibertyReserve['store'] %>" />
  <input type="hidden" name="lr_merchant_ref" value="<%= @current_user.id %>" />
  <input type="hidden" name="lr_comments" value="Transfer funds to account <%= @current_user.account %>" />

  <input type="hidden" name="lr_success_url" value="<%= BitcoinBank::LibertyReserve['success_url'] %>" />
  <input type="hidden" name="lr_success_url_method" value="GET" />

  <input type="hidden" name="lr_fail_url" value="<%= BitcoinBank::LibertyReserve['fail_url'] %>" />
  <input type="hidden" name="lr_fail_url_method" value="GET" />

  <input type="hidden" name="lr_status_url" value="<%= BitcoinBank::LibertyReserve['status_url'] %>" />
  <input type="hidden" name="lr_status_url_method" value="POST" />

  <input type="hidden" name="account_id" value="<%= @current_user.id %>" />
</form>

<p> <%= t :click_for_lr_html, :action => "$('#add_lr').submit();" %> </p>

app/views/transfers/_px_sci_form.html.erb
<form id="pecunix-sci-form" action="https://pri.pecunix.com/money.refined" method="post">
  <input type="hidden" name="PAYEE_ACCOUNT" value="<%= config["account"] %>" />
  <input name="PAYMENT_AMOUNT" value="<%= amount %>" />

  <input type="hidden" name="PAYMENT_URL" value="<%= config["payment_url"] %>" />
  <input type="hidden" name="PAYMENT_URL_METHOD" value="GET" />

  <input type="hidden" name="NOPAYMENT_URL" value="<%= config["no_payment_url"] %>" />
  <input type="hidden" name="NOPAYMENT_URL_METHOD" value="GET" />

  <input type="hidden" name="STATUS_URL" value="<%= config["status_url"] %>" />
  <input type="hidden" name="STATUS_TYPE" value="FORM" />

  <input type="hidden" name="INPUT_HASH" value="<%= hash %>" />

  <input type="hidden" name="PAYMENT_UNITS" value="GAU" />
  <input type="hidden" name="WHO_PAYS_FEES" value="PAYEE" />
  <input type="hidden" name="PAYMENT_ID" value="<%= payment_id %>" />

  <input type="hidden" name="SUGGESTED_MEMO" value="Transfer funds to account <%= @current_user.account %>" />
</form>

app/views/transfers/index.html.haml
%h1= t :account_history_title

%table#history.default
  %tr
    %th Date
    %th= t :currency
    %th= t :amount
    %th.auto-sized

  - unless @transfers.blank?
    - @transfers.each do |transfer|
      %tr{ :class => cycle('even', 'odd') }
        %td= l transfer.created_at
        %td
          = currency_icon_for(transfer.currency)
          = transfer.currency
        %td.amount
          %span{ :class => color_for(transfer), :title => confirmation_tooltip_for(transfer) }
            = "#{transfer.amount > 0 ? "+" : "-"} #{number_to_currency transfer.amount.abs, :unit => ""}"
        %td.auto-sized
          = transfer_details(transfer)  

  - else
    = render :partial => "layouts/no_data"

= will_paginate(@transfers)

app/views/transfers/new.html.haml
%h1= t(".title")
= t(".body_html")

%br

= form_for @transfer, :as => :transfer, :url => account_transfers_path do |f|
  = errors_for(@transfer, :translated_message => t(".error"), :include_nested => :bank_account)

  .form-field
    = f.label :currency
    = f.select :currency, [["Bitcoins", "BTC"], ["EUR", "EUR"], ["Liberty Reserve USD", "LRUSD"], ["Liberty Reserve EUR", "LREUR"]]
  
  - if @transfer.currency == "BTC"
    .form-field
      = f.label :address
      = f.text_field :address

  - if ["LRUSD", "LREUR"].include? @transfer.currency
    .form-field
      = f.label :lr_account_id
      = f.text_field :lr_account_id

  - if @transfer.currency == "EUR"
    - if @bank_accounts.blank? && @transfer.bank_account_id.blank?
      = f.fields_for :bank_account do |bank_account|
        = render :partial => 'bank_accounts/fields', :locals => { :form_builder => bank_account }
    - else
      .form-field
        = f.label :bank_account_id
        = f.select :bank_account_id, @bank_accounts, {}, { :prompt => "--" }
        .explanation= link_to t(".manage_bank_accounts"), user_bank_accounts_path
        
  .form-field
    = label_tag :max_amount, t(".max_amount")
    = text_field_tag :max_amount, amount_field_value(current_user.max_withdraw_for(@transfer.currency)), :class => "amount", :disabled => true

  .form-field
    = f.label :amount
    = f.text_field :amount, :value => amount_field_value(@transfer.amount), :autocomplete => "off"
    
  .form-field
    = f.submit :value => t(".submit"), :class => "submit"

app/views/transfers/show.html.haml
%h1
  Transaction n°
  %span.fixed= @transfer.id

%table.default.details
  %tr
    %th= t("activerecord.attributes.transfer.id")
    %td.fixed= @transfer.id

  %tr
    %th= t("activerecord.attributes.transfer.created_at")
    %td= l(@transfer.created_at)

  - if @transfer.is_a?(Transfer)
    %tr
      %th= t("activerecord.attributes.transfer.state")
      %td= transfer_state(@transfer.state, :message => t(".state.#{@transfer.state}").html_safe, :icon => true)

  %tr
    %th= t("activerecord.attributes.transfer.amount")
    %td.fixed= number_to_currency(@transfer.amount, :unit => "", :precision => 6)

  %tr
    %th= t("activerecord.attributes.transfer.currency")
    %td
      = currency_icon_for(@transfer.currency)
      = @transfer.currency

  - if @transfer.bt_tx_id
    %tr
      %th= t("activerecord.attributes.transfer.bt_tx_id")
      %td.fixed= bbe_link(:tx, @transfer.bt_tx_id)

  - if @transfer.bt_tx_confirmations and @transfer.bt_tx_confirmations > 0
    %tr
      %th= t("activerecord.attributes.transfer.bt_tx_confirmations")
      %td.fixed= @transfer.bt_tx_confirmations

  - if @transfer.lr_transaction_id
    %tr
      %th= t("activerecord.attributes.transfer.lr_transaction_id")
      %td.fixed= @transfer.lr_transaction_id

  - if @transfer.px_tx_id
    %tr
      %th= t("activerecord.attributes.transfer.px_tx_id")
      %td.fixed= @transfer.px_tx_id

  - if @transfer.respond_to? :bank_account
    %tr
      %th= t("activerecord.models.bank_account.one")
      %td.fixed= @transfer.bank_account.iban

  - unless @transfer.comment.blank?
    %tr
      %th= t("activerecord.attributes.transfer.comment")
      %td
        %pre= @transfer.comment